version: '3.5'

services:
  traefik:
    image: traefik:v2.5
    container_name: "traefik"
    command: 
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=jannik@feuer.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefikdash.rule=Host(`traefik.feuer.dev`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefikdash.entrypoints=websecure"
      - "traefik.http.routers.traefikdash.service=api@internal"
      - "traefik.http.routers.traefikdash.tls.certresolver=letsencrypt"
      - "traefik.http.services.traefikdash.loadbalancer.server.port=8080"
    networks:
      - jnet
  jenkins:
    image: "jenkins/jenkins:lts-jdk11"
    container_name: "jenkins"
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - "jenkins_home:/var/jenkins_home"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`jenkins.feuer.dev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    networks:
      - jnet
volumes:
  jenkins_home:

networks:
  jnet:
    name: jnet